---
language: ruby
cache: bundler
rvm:
  - 2.6
  - 2.7
  - 3.0
  - 3.1
gemfile:
  - Gemfile
  - gemfiles/rails-6.1.x.gemfile
jobs:
  exclude:
    # Exclude rubies < 2.7 for ActiveModel < 7.0
    - rvm: 2.6
      gemfile: Gemfile

# Force Travis jobs to use the latest version of Bundler
before_install:
  - yes | gem update --system --force
  - gem install bundler

before_script:
  - "cd spec/dummy && bundle exec rake db:drop db:create db:schema:load db:test:prepare && cd -"
script:
  - "bundle exec rake spec"
